# Generated by Django 4.2.4 on 2023-08-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EApp', '0002_remove_order_ordered_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.PositiveIntegerField()),
                ('ordered_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EApp.product')),
                ('order_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='EApp.order')),
            ],
        ),
    ]
